source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.0'

gem 'rails', '7.1.0'
gem 'sass-rails', '6.0.0'
gem 'uglifier'

gem 'dynamic_form'

gem 'roar', '1.0.2'
gem 'representable', '2.3.0'

gem 'js-routes', '>= 1.4.12'
gem 'versionist', '>= 2.0.0'

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', '>= 1.2018.6', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

group :development, :test do
  # we use `jasmine` gem + `selenium-webdriver` for the `jasmine:ci` task
  # this task will run jasmine in a browser, driven by selenium
  gem 'jasmine', '>= 3.3.0'
  gem 'jasmine-jquery-rails'
  gem 'jasmine_selenium_runner'

  gem 'ruby-debug-base'
  gem 'ruby-debug-ide', '0.7.0'

  # make sure to `System.setProperty("jruby.runtime.arguments", "--debug")` before opening up pry
  gem 'pry-debugger-jruby'
end

group :test do
  gem 'capybara', '2.16.0'
  gem 'rspec-rails', '>= 3.8.1'
  gem 'rspec-instafail', require: false
  gem 'rspec_junit_formatter'
  gem 'rails-controller-testing', '>= 1.0.3'
end

group :development do
  gem 'scss_lint', require: false
  gem 'brakeman', require: false
  gem 'bundler-audit', require: false
  gem 'ruby_audit', require: false
end
